encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path('wiki/<str:title>', views.entry, name="entry"),
    path('add', views.add, name="add"),
    path('search', views.search, name="search"),
    path('random', views.render_random, name="random"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import random, markdown2

from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django import forms
from django.urls import reverse

from . import util


class NewEntryForm(forms.Form):
    title = forms.CharField(
        label = "Title", 
        widget = forms.TextInput(attrs={
            'placeholder': 'Title here'
        })
    )
    content = forms.CharField(
        label = "Content", 
        widget = forms.Textarea(attrs={
            'placeholder': 'Write the content here using Mardown2 markup language.'
        })
    )

msg_notfound = ('#Page not found\n'
    'We are **sorry** to announce that the page you are looking for has '
    'not been **created** yet.\n\n'
    'You might be the first creator to **write** it!'
)

msg_aldycreated = ('#####The page you just submitted already exists!\n'
    'A page with the **same title** already exists in the wiki.\n\n'
    '**Check it out** searching for it or try again.'
)

msg_invalidform = ('#####Sorry, it looks like there is something wrong!\n'
    'We could not add you page because the **title** or **content** you just submitted is **not valid**.\n\n '
    'Please **try again**.'
)


def index(request):
        return render(request, "encyclopedia/index.html", {
                "entries": util.list_entries()
        })


def entry(request, title):
    if 'edit' in request.GET:
        editform = NewEntryForm(
            initial={
                'title': title, 
                'content': util.get_entry(title)
            })
        return render(request, "encyclopedia/add.html", {
            "edit" : request.GET["edit"],
            "title": title,
            "form": editform
        })
    else:
        if title in util.list_entries():
            return render(request, "encyclopedia/entry.html", {
                "title": title,
                "content": util.decode(title)
            })
        else:
            return render(request, "encyclopedia/entry.html", {
                "title": "Page not found",
                "content": markdown2.markdown(msg_notfound)
            })


def add(request):
    if request.method == "POST":
        # stores the data retrieved from the POST request into the object inputform
        inputform = NewEntryForm(request.POST)
        edit = request.POST["edit"]
        # if form is valid(server side validation)
        if inputform.is_valid():
            # takes the string in the attribute "task" and content from the object inputform 
            # and stores it in a variables called title and content 
            title = inputform.cleaned_data["title"]
            content = inputform.cleaned_data["content"]
            # check if there is the entry is repeated and store it in variable
            repeated = (title.upper() in [x.upper() for x in util.list_entries()])
            # write in file
            if edit == "true" or not repeated:
                util.save_entry(title,content)
                return render(request, "encyclopedia/entry.html", {
                  "title": title,
                  "content": util.decode(title)
                })
            else:
                return render(request, "encyclopedia/add.html", {
                    "edit": edit,
                    "form": inputform,
                    "msg": markdown2.markdown(msg_aldycreated)
                })
        # in case form is not valid, send back the form 
        else:
            return render(request, "encyclopedia/add.html", {
                "edit": edit,
                "form": inputform,
                "msg": markdown2.markdown(msg_invalidform)
            })
    elif request.method == "GET":
        return render(request, "encyclopedia/add.html", {
                "edit": "false",
                "form": NewEntryForm(),
        })


def search(request):
    if request.method == "GET":
        target = request.GET['q']
        for entry in util.list_entries():
            if target.upper() == entry.upper():
                return redirect('encyclopedia:entry', title=entry)
        else:
            return render(request, "encyclopedia/search.html", {
                "results": util.match(target),
                "title": target
        })


def render_random(request):
    random_title = random.choice(util.list_entries())
    return redirect('encyclopedia:entry', title=random_title)

encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  {% if edit == "true" %}
    Edit Page - Wiki
  {% else %}
    Create New Page - Wiki
  {% endif %}
{% endblock %}

{% block body %}
  {% if edit == "true" %}
    <h1>Edit Page:</h1>
  {% else %}
    <h1>Create New Page:</h1>
  {% endif %}
  <!-- error message -->
  {{ msg|safe }}
  <form action="{% url 'encyclopedia:add' %}" method="post">
    <!-- csrf middelware token to fulfill cross site request forgery protection default by django -->
    {% csrf_token %}
    <!-- rendering fields manually to be able to style them -->
    {{ form.non_field_errors }}
    <div class="titleWrapper">
        {{ form.title.errors }}
        <label for="{{ form.title.id_for_label }}">Title:</label>
        {{ form.title }}
    </div>
    <div class="contentWrapper">
        {{ form.content.errors }}
        <div for="{{ form.content.id_for_label }}">Content:</div>
        {{ form.content }}
    </div>
    {% if edit == "true" %}
      <input type="hidden" name="edit" value="true">
    {% else %}
      <input type="hidden" name="edit" value="false">
    {% endif %}
    <input type="submit">
  </form>
  <a href="{% url 'encyclopedia:index' %}">View Entries</a>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  {{title}} - Wiki
{% endblock %}

{% block body %}
  {{content|safe}}
  <form action="{% url 'encyclopedia:entry' title%}" method="GET">
    <button type="submit" name="edit" value="true">Edit</button>
  </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
  <h1>All Pages</h1>
  <ul>
    {% for entry in entries %}
      <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                  <a href="{% url 'encyclopedia:add' %}">Create New Page</a>
                </div>
                <div>
                  <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  {{ title }} - Wiki Search
{% endblock %}

{% block body %}
  <h1>Results for "{{ title }}" </h1>
  <ul>
    {% for entry in results %}
      <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
    {% empty %}
      <li>No results found</li>
    {% endfor %}
  </ul>
{% endblock %}